all:
	ocp-build ocplib-coff ocp-coff

test-read-library:
	../../_obuild/ocp-coff/ocp-coff.asm /usr/lib/gcc/i686-w64-mingw32/4.6/*.a

test-read-program:
	../../_obuild/ocp-coff/ocp-coff.asm /home/lefessan/WindowsSharedFolder/Binary-Archives/mingw-builds-install.exe

test-read-object:
	../../_obuild/ocp-coff/ocp-coff.asm /usr/lib/gcc/i686-w64-mingw32/4.6/*.o

test-read-dll:
	../../_obuild/ocp-coff/ocp-coff.asm /usr/lib/gcc/i686-w64-mingw32/4.6/*.dll


